### ISSUE TITLE
[EPIC: Module  02] Setting up Environment

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#122]
- [ ] Create Notebook_01_Installation.ipynb
- [ ] Create Notebook_02_Configuration.ipynb
- [ ] Create Notebook_03_Project_Initialization.ipynb
