### ISSUE TITLE
[EPIC: Module 04] Prompting

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#124]
- [ ] Create Notebook_01_Introduction_to_Prompts.ipynb
- [ ] Create Notebook_02_Prompt_Templates.ipynb
- [ ] Create Notebook_03_System_Context_Conversations .ipynb
