### ISSUE TITLE
[EPIC: MODULE 05] Deploying Applications

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#125]
- [ ] Create Notebook_01_Gradio_Basics.ipynb
- [ ] Create Notebook_02_Streamlit_Basics.ipynb
- [ ] Create Notebook_03_Deployment_Walkthrough.ipynb
