### ISSUE TITLE
[EPIC: Module 08] Document Parsers

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#128]
- [ ] Create Notebook_01_Parser_Overview.ipynb
- [ ] Create Notebook_02_Parser_Customization
- [ ] Create Notebook_03_Integration_Techniques.ipynb
