### ISSUE TITLE
[EPIC: Module 09] Documents and Embeddings

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#129]
- [ ] Create Notebook_01_Embedding_Techniques
- [ ] Create Notebook_02_Data_Transformation.ipynb
- [ ] Create Notebook_03_Handling_Embedded_Documents.ipynb
