### ISSUE TITLE
[EPIC: Module 10] Vector Stores and Retrieval

### ISSUE THREAD

**Issue by Mariam-Adisa** [swarmauri/swarmauri-notebooks#136]
- [ ] Create Notebook 01 Configuring Vector Stores.ipynb
- [ ] Create Notebook 02 Search Strategies.ipynb
- [ ] Create Notebook 03 Vector Based Search.ipynb
