### ISSUE TITLE
[EPIC: Module 11] RAG Agent

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#137]
- [ ] Create Notebook 01 Understanding RAG framework.ipynb
- [ ] Create Notebook 02 Vector Store Integration.ipynb
- [ ] Create Notebook 03 Building RAG Agents.ipynb
