### ISSUE TITLE
[EPIC Module 14] Capstone Project Part 1

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#140]
- [ ] Notebook 01 Project Proposal.ipynb
- [ ] Notebook 02 Design and Planning.ipynb
- [ ] Notebook 03 Initial Setup.ipynb
