### ISSUE TITLE
[EPIC: Module 15] Capstone Project Part  2

### ISSUE THREAD

**Issue by DevDigiLance** [swarmauri/swarmauri-notebooks#141]
- [ ] Notebook 01 Development and implementation.ipynb
- [ ] Notebook 02Testing and Refinement.ipynb
- [ ] Notebook 03 Documentation and Presentation.ipynb
